'use client'

import { Recommendation } from '@/types'
import { CheckCircle, AlertTriangle, ArrowRight, Download } from 'lucide-react'

interface Props {
  recommendation: Recommendation
  moduleTitle: string
}

export default function RecommendationOutput({ recommendation, moduleTitle }: Props) {
  function exportMarkdown() {
    const md = [
      `# Azure Recommendation: ${moduleTitle}`,
      ``,
      `## ${recommendation.headline}`,
      ``,
      `## Recommendation`,
      recommendation.recommendation,
      ``,
      `## Rationale`,
      recommendation.rationale,
      ``,
      `## Trade-offs`,
      recommendation.tradeoffs.map((t) => `- ${t}`).join('\n'),
      ``,
      `## Estimated Cost`,
      recommendation.costRange,
      ``,
      `## Next Steps`,
      recommendation.nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n'),
      ``,
      `## Risks`,
      recommendation.risks.map((r) => `- ${r}`).join('\n'),
      ``,
      `---`,
      `*Generated by Azure Decision Helper — ${new Date().toLocaleDateString('en-AU')}*`,
    ].join('\n')

    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `azure-recommendation-${Date.now()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-950 to-slate-900 px-4 py-12">
      <div className="max-w-3xl mx-auto">

        {/* Header */}
        <div className="mb-8">
          <p className="text-blue-400 text-sm font-medium mb-1">{moduleTitle}</p>
          <h1 className="text-3xl font-bold text-white">{recommendation.headline}</h1>
        </div>

        {/* Cost badge */}
        <div className="inline-flex items-center gap-2 bg-emerald-900/40 border border-emerald-700 rounded-full px-4 py-1.5 text-emerald-400 text-sm font-medium mb-8">
          <span>💰</span>
          {recommendation.costRange}
        </div>

        {/* Recommendation */}
        <section className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6 mb-5">
          <h2 className="text-lg font-semibold text-white mb-3">Recommendation</h2>
          <div className="text-slate-300 leading-relaxed whitespace-pre-line">{recommendation.recommendation}</div>
        </section>

        {/* Rationale */}
        <section className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6 mb-5">
          <h2 className="text-lg font-semibold text-white mb-3">Why this fits your context</h2>
          <p className="text-slate-300 leading-relaxed">{recommendation.rationale}</p>
        </section>

        {/* Two-col: Tradeoffs + Risks */}
        <div className="grid md:grid-cols-2 gap-5 mb-5">
          <section className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6">
            <h2 className="text-lg font-semibold text-white mb-3">Trade-offs</h2>
            <ul className="space-y-2">
              {recommendation.tradeoffs.map((t, i) => (
                <li key={i} className="flex gap-2.5 text-slate-300 text-sm">
                  <AlertTriangle size={16} className="text-amber-400 mt-0.5 shrink-0" />
                  {t}
                </li>
              ))}
            </ul>
          </section>

          <section className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6">
            <h2 className="text-lg font-semibold text-white mb-3">Risks</h2>
            <ul className="space-y-2">
              {recommendation.risks.map((r, i) => (
                <li key={i} className="flex gap-2.5 text-slate-300 text-sm">
                  <AlertTriangle size={16} className="text-red-400 mt-0.5 shrink-0" />
                  {r}
                </li>
              ))}
            </ul>
          </section>
        </div>

        {/* Next steps */}
        <section className="bg-blue-950/60 border border-blue-800 rounded-2xl p-6 mb-8">
          <h2 className="text-lg font-semibold text-white mb-4">Next Steps</h2>
          <ol className="space-y-3">
            {recommendation.nextSteps.map((step, i) => (
              <li key={i} className="flex gap-3 text-slate-200 text-sm">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 rounded-full flex items-center justify-center text-xs font-bold text-white">
                  {i + 1}
                </span>
                {step}
              </li>
            ))}
          </ol>
        </section>

        {/* Actions */}
        <div className="flex flex-wrap gap-3">
          <button
            onClick={exportMarkdown}
            className="flex items-center gap-2 px-5 py-2.5 bg-slate-700 hover:bg-slate-600 text-white rounded-lg font-medium transition-colors text-sm"
          >
            <Download size={16} />
            Export as Markdown
          </button>
          <a
            href="/"
            className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-medium transition-colors text-sm"
          >
            Run another assessment
            <ArrowRight size={16} />
          </a>
        </div>
      </div>
    </div>
  )
}
