'use client'

import { useState } from 'react'
import { Recommendation } from '@/types'
import { AlertTriangle, ArrowRight, Download, RefreshCw, MessageSquarePlus, ChevronDown, ChevronUp, Sparkles } from 'lucide-react'
import clsx from 'clsx'

interface Props {
  recommendation: Recommendation
  moduleTitle: string
  moduleId?: string
}

export default function RecommendationOutput({ recommendation: initial, moduleTitle, moduleId }: Props) {
  const [current, setCurrent] = useState<Recommendation>(initial)
  const [isRefined, setIsRefined] = useState(false)
  const [refinementHistory, setRefinementHistory] = useState<Recommendation[]>([])

  const [feedbackOpen, setFeedbackOpen] = useState(false)
  const [feedback, setFeedback] = useState('')
  const [refining, setRefining] = useState(false)
  const [refineError, setRefineError] = useState<string | null>(null)

  function exportMarkdown() {
    const md = [
      `# Azure Recommendation: ${moduleTitle}${isRefined ? ' (Refined)' : ''}`,
      ``,
      `## ${current.headline}`,
      ``,
      `## Recommendation`,
      current.recommendation,
      ``,
      `## Rationale`,
      current.rationale,
      ``,
      `## Trade-offs`,
      current.tradeoffs.map((t) => `- ${t}`).join('\n'),
      ``,
      `## Estimated Cost`,
      current.costRange,
      ``,
      `## Next Steps`,
      current.nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n'),
      ``,
      `## Risks`,
      current.risks.map((r) => `- ${r}`).join('\n'),
      ``,
      `---`,
      `*Generated by Azure Decision Helper — ${new Date().toLocaleDateString('en-AU')}*`,
    ].join('\n')

    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `azure-recommendation-${Date.now()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  async function submitRefinement() {
    if (!feedback.trim() || !moduleId) return
    setRefining(true)
    setRefineError(null)
    try {
      const res = await fetch('/api/refine', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          moduleId,
          originalRecommendation: current,
          feedback: feedback.trim(),
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Request failed')

      setRefinementHistory((prev) => [...prev, current])
      setCurrent(data.recommendation)
      setIsRefined(true)
      setFeedback('')
      setFeedbackOpen(false)
      window.scrollTo({ top: 0, behavior: 'smooth' })
    } catch (e) {
      setRefineError(e instanceof Error ? e.message : 'Something went wrong. Please try again.')
    } finally {
      setRefining(false)
    }
  }

  function revertToPrevious() {
    if (refinementHistory.length === 0) return
    const prev = refinementHistory[refinementHistory.length - 1]
    setCurrent(prev)
    setRefinementHistory((h) => h.slice(0, -1))
    setIsRefined(refinementHistory.length > 1)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-950 to-slate-900 px-4 py-12">
      <div className="max-w-3xl mx-auto">

        {/* Header */}
        <div className="mb-4">
          <div className="flex items-center gap-3 mb-1">
            <p className="text-blue-400 text-sm font-medium">{moduleTitle}</p>
            {isRefined && (
              <span className="inline-flex items-center gap-1 bg-violet-900/50 border border-violet-600 rounded-full px-2.5 py-0.5 text-violet-300 text-xs font-medium">
                <Sparkles size={11} />
                Refined
              </span>
            )}
          </div>
          <h1 className="text-3xl font-bold text-white">{current.headline}</h1>
        </div>

        {/* Revert link */}
        {refinementHistory.length > 0 && (
          <button
            onClick={revertToPrevious}
            className="flex items-center gap-1.5 text-slate-500 hover:text-slate-300 text-xs mb-6 transition-colors"
          >
            <RefreshCw size={12} />
            Revert to previous recommendation
          </button>
        )}
        {!refinementHistory.length && <div className="mb-6" />}

        {/* Cost badge */}
        <div className="inline-flex items-center gap-2 bg-emerald-900/40 border border-emerald-700 rounded-full px-4 py-1.5 text-emerald-400 text-sm font-medium mb-8">
          <span>💰</span>
          {current.costRange}
        </div>

        {/* Recommendation */}
        <section className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6 mb-5">
          <h2 className="text-lg font-semibold text-white mb-3">Recommendation</h2>
          <div className="text-slate-300 leading-relaxed whitespace-pre-line">{current.recommendation}</div>
        </section>

        {/* Rationale */}
        <section className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6 mb-5">
          <h2 className="text-lg font-semibold text-white mb-3">Why this fits your context</h2>
          <p className="text-slate-300 leading-relaxed">{current.rationale}</p>
        </section>

        {/* Two-col: Tradeoffs + Risks */}
        <div className="grid md:grid-cols-2 gap-5 mb-5">
          <section className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6">
            <h2 className="text-lg font-semibold text-white mb-3">Trade-offs</h2>
            <ul className="space-y-2">
              {current.tradeoffs.map((t, i) => (
                <li key={i} className="flex gap-2.5 text-slate-300 text-sm">
                  <AlertTriangle size={16} className="text-amber-400 mt-0.5 shrink-0" />
                  {t}
                </li>
              ))}
            </ul>
          </section>

          <section className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6">
            <h2 className="text-lg font-semibold text-white mb-3">Risks</h2>
            <ul className="space-y-2">
              {current.risks.map((r, i) => (
                <li key={i} className="flex gap-2.5 text-slate-300 text-sm">
                  <AlertTriangle size={16} className="text-red-400 mt-0.5 shrink-0" />
                  {r}
                </li>
              ))}
            </ul>
          </section>
        </div>

        {/* Next steps */}
        <section className="bg-blue-950/60 border border-blue-800 rounded-2xl p-6 mb-8">
          <h2 className="text-lg font-semibold text-white mb-4">Next Steps</h2>
          <ol className="space-y-3">
            {current.nextSteps.map((step, i) => (
              <li key={i} className="flex gap-3 text-slate-200 text-sm">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 rounded-full flex items-center justify-center text-xs font-bold text-white">
                  {i + 1}
                </span>
                {step}
              </li>
            ))}
          </ol>
        </section>

        {/* Feedback / Refine section */}
        <section className="border border-slate-700 rounded-2xl mb-8 overflow-hidden">
          <button
            onClick={() => setFeedbackOpen((o) => !o)}
            className="w-full flex items-center justify-between px-6 py-4 bg-slate-800/40 hover:bg-slate-800/70 transition-colors text-left"
          >
            <div className="flex items-center gap-2.5">
              <MessageSquarePlus size={17} className="text-violet-400" />
              <span className="text-white font-medium text-sm">This doesn&apos;t fit our setup — refine the recommendation</span>
            </div>
            {feedbackOpen
              ? <ChevronUp size={16} className="text-slate-400" />
              : <ChevronDown size={16} className="text-slate-400" />
            }
          </button>

          {feedbackOpen && (
            <div className="px-6 pb-6 pt-4 bg-slate-800/20">
              <p className="text-slate-400 text-sm mb-4">
                Tell us what doesn&apos;t fit — your existing setup, specific constraints, technology choices, or anything the recommendation got wrong. Claude will refine it based on your context.
              </p>
              <textarea
                value={feedback}
                onChange={(e) => setFeedback(e.target.value)}
                placeholder="e.g. We already have an existing AKS cluster we can't replace. Our security team won't allow public endpoints. We're locked into Terraform and can't use Bicep. Our budget is capped at $500/month..."
                rows={5}
                className="w-full bg-slate-900/60 border border-slate-700 focus:border-violet-500 focus:ring-1 focus:ring-violet-500 rounded-xl px-4 py-3 text-white placeholder:text-slate-600 text-sm leading-relaxed resize-none outline-none transition-all mb-3"
              />
              {refineError && (
                <p className="text-red-400 text-sm mb-3">{refineError}</p>
              )}
              <div className="flex items-center justify-between">
                <p className="text-slate-600 text-xs">The more specific you are, the better the refinement.</p>
                <button
                  onClick={submitRefinement}
                  disabled={!feedback.trim() || refining}
                  className={clsx(
                    'flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-sm transition-all',
                    feedback.trim() && !refining
                      ? 'bg-violet-600 hover:bg-violet-500 text-white'
                      : 'bg-slate-700 text-slate-500 cursor-not-allowed'
                  )}
                >
                  {refining ? (
                    <>
                      <span className="inline-block w-4 h-4 border-2 border-slate-400 border-t-white rounded-full animate-spin" />
                      Refining...
                    </>
                  ) : (
                    <>
                      <Sparkles size={15} />
                      Refine recommendation
                    </>
                  )}
                </button>
              </div>
            </div>
          )}
        </section>

        {/* Actions */}
        <div className="flex flex-wrap gap-3">
          <button
            onClick={exportMarkdown}
            className="flex items-center gap-2 px-5 py-2.5 bg-slate-700 hover:bg-slate-600 text-white rounded-lg font-medium transition-colors text-sm"
          >
            <Download size={16} />
            Export as Markdown
          </button>
          <a
            href="/"
            className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-medium transition-colors text-sm"
          >
            Run another assessment
            <ArrowRight size={16} />
          </a>
        </div>
      </div>
    </div>
  )
}
